
services:
  app:
    build: ./app/
    ports:
      - 5050:5050
  
  model:
    image: codait/max-text-summarizer
    ports:
      - 5000:5000
  
  db:
    image: postgres
    ports:
      - 5432:5432 
    volumes: 
      - db_data:/var/lib/postgres/data
    environment: 
      PGDATA: /var/lib/postgres/data 
      POSTGRES_USER: virginie
      POSTGRES_PASSWORD: mysecretpassword
      
volumes:
  db_data:



# fonctionne si le nom du service est mis dans le script db_utilis.py