
services:
  app:
    build: ./app/
    ports:
      - 5050:5050
    volumes:
      - ./app/wym:/app/
    depends_on:
      - model
      - db 
  
  model:
    image: codait/max-text-summarizer
    ports:
      - 5000:5000
    
  
  db:
    image: postgres
    ports:
      - 5432:5432 
    volumes: 
      - db_data:/var/lib/postgres/data
    environment: 
      PGDATA: /var/lib/postgres/data 
      POSTGRES_USER: virginie
      POSTGRES_PASSWORD: mysecretpassword
      
volumes:
  db_data: